---

- hosts: masters[0]
  become: yes
  name: Add automator service account
  roles:
    - ocp_create_master_service_account
  vars:
    - sa_name: automator
    - cluster_role: cluster-admin
    - project: openshift-infra